[
{"href":"http://www.thelocalpapers.com/by_country.html","title":"Diarios del mundo"},
{"href":"http://www.clarin.com/","title":"ARG Clarin"},
{"href":"https://www.larazon.es/tags/argentina/","title":"ARG LaRazon"},
{"href":"http://www.lanacion.com.ar/","title":"ARG LaNacion"},

{"href":"http://www.diarioelpais.com/?","title":"URU ElPais"},
{"href":"http://www.observa.com.uy/","title":"URU ElObservador"},
{"href":"http://www.brecha.com.uy/","title":"URU Brecha"},
{"href":"http://www.editorandpublisher.com/","title":"Editor&Pub"},

{"href":"http://www.europapress.es/","title":"Europa Press"},
{"href":"http://www.washingtonpost.com/wp-dyn/opinion/","title":"WashPost"},
{"href":"http://www.washtimes.com/op-ed/","title":"WashTimes"},
{"href":"http://www.nypost.com","title":"NYPost"},
{"href":"http://www.wsj.com","title":"Wall Street Journal"},
{"href":"http://www.nytimes.com/","title":"NYTimes"},
{"href":"https://www.arkansasonline.com/","title":"ArkDemGaz"},
{"href":"http://www.nydailynews.com/","title":"NYDailyNews"},
{"href":"http://nysun.com/","title":"NYSun"},

{"href":"http://www.boston.com/","title":"BostonGlobe"},
{"href":"https://www.bostonherald.com/","title":"BostonHerald"},
{"href":"http://www.latimes.com","title":"LATimes"},
{"href":"http://www.suntimes.com/index/commentary.html","title":"ChiSunTimes"},
{"href":"http://www.usatoday.com/news/comment/debate.htm","title":"USAToday"},
{"href":"http://www.theunionleader.com/","title":"ManchUnionLead"},
{"href":"http://www.dallasnews.com/editorial/","title":"DallMornNews"},
{"href":"http://www.chicago.tribune.com/news/opinion/","title":"ChiTribune"},
{"href":"http://www.chron.com/content/news/editorial/index.html","title":"HouChronicle"},
{"href":"http://www.seattletimes.com/news/editorial","title":"SeaTimes"},
{"href":"https://www.sfgate.com/","title":"SFExaminer"},
{"href":"http://www.herald.com/opinion/","title":"MiaHerald"},
{"href":"http://www.sunspot.net/opinion/","title":"BaltoSun"},
{"href":"http://www.sjmercury.com/opinion/","title":"SJMercuryNews"},
{"href":"http://www.opinionjournal.com/","title":"WSJournal"},
{"href":"http://www.thetimes.co.uk","title":"UK Times"},
{"href":"https://www.telegraph.co.uk/","title":"UK Telegraph"},
{"href":"http://www.mirror.co.uk/","title":"UK DailyMirror"},
{"href":"http://www.independent.co.uk/","title":"UK Independ"},

{"href":"https://www.theguardian.com/us","title":"UK Guardian"},
{"href":"http://www.iht.com/","title":"Int.Herald Trib."},

{"href":"http://www.parissoir.com/","title":"FRA Paris Soir"},
{"href":"http://www.lemonde.fr/","title":"FRA Le Monde"},
{"href":"http://www.lefigaro.fr/","title":"FRA Le Figaro"},
{"href":"http://www.lexpress.fr/info/","title":"FRA L'Express"},
{"href":"http://www.liberation.fr/","title":"FRA Liberation"},
{"href":"http://www.corriere.it/","title":"ITA CorriereDellaSera"},
{"href":"http://www.unita.it/","title":"ITA L'Unita"},
{"href":"http://www.elpais.es/","title":"ESP El Pais"},
{"href":"http://www.elmundo.es/","title":"ESP El Mundo"},
{"href":"http://www.abc.es/","title":"ESP ABC"},
{"href":"http://www.elperiodico.com/","title":"ESP El Periodico"},
{"href":"http://www.csmonitor.com/commentary/index.html","title":"ChristianScienceMon"}


]