[
{"href":"http://www.pcmag.com/","title":"PC Magazine"},
{"href":"http://www.zdnet.com/","title":"ZDnet"},
{"href":"http://www.internet.com/","title":"Internet"},
{"href":"http://www.ecommercetimes.com/","title":"eCommerceTimes"},
{"href":"http://www.business2.com/","title":"Business2.0"},
{"href":"http://webdevelopersjournal.com/","title":"WebDevJournal"},
{"href":"http://www.intelligententerprise.com/","title":"Intelligent Ent."},
{"href":"http://www.internetweek.com/","title":"InternetWeek"},
{"href":"http://www.15seconds.com/","title":"15Seconds"},
{"href":"http://www.winntmag.com/","title":"WindowsNT Mag."},
{"href":"http://msdn.microsoft.com/msdnmag/","title":"MSDN"},
{"href":"http://www.sdmagazine.com/","title":"SoftwareDev "},
{"href":"http://accessvbsqladvisor.com/","title":"VB/SQL Advisor "},
{"href":"http://vbwire.com/","title":"VB Wire"},
{"href":"http://www.vbwm.com/","title":"VB WebMag"},
{"href":"http://www.fawcette.com/vsm/","title":"VisualStudioMag "},
{"href":"http://www.digitalimagingmag.com/","title":"DigitalImaging"},
{"href":"http://www.informationweek.com/","title":"InformationWeek"},
{"href":"http://www.infoworld.com/","title":"InfoWorld"},
{"href":"http://www.webtechniques.com/","title":"NewArchitect"},
{"href":"http://www.business2.com/","title":"Business2.0"},
{"href":"http://www.pcworld.com/","title":"PCWorld"},
{"href":"http://www.fawcette.com/xmlmag/","title":"XML Magazine"},
{"href":"http://www.sqlmag.com/","title":"SQL Server Magazine"},
{"href":"http://www.internet.com/home-d.html","title":"Internet Magazine"}
]