[
{"href":"http://www.pcmag.com/","title":"PC Magazine"},
{"href":"http://www.pcworld.com/","title":"PCWorld"},
{"href":"http://www.zdnet.com/","title":"ZDnet"},
{"href":"http://www.internet.com/","title":"Internet"},
{"href":"http://www.ecommercetimes.com/","title":"eCommerceTimes"},
{"href":"https://www.fortune.com/","title":"Fortune"},
{"href":"https://www.informationweek.com/","title":"InformationWeek"},
{"href":"https://www.codemag.com/Magazine/ByCategory/JSON","title":"JSON"},
{"href":"http://msdn.microsoft.com/msdnmag/","title":"MSDN"},
{"href":"http://www.sdmagazine.com/","title":"SoftwareDev "},
{"href":"https://www.sqlservergeeks.com/the-scripts-garage/","title":"SQL Scripts"},
{"href":"https://visualstudiomagazine.com/articles/list/c.aspx","title":"C# Mag"},
{"href":"https://visualstudiomagazine.com/Articles/List/Visual-Basic.aspx","title":"VB WebMag"},
{"href":"https://visualstudiomagazine.com/home.aspx","title":"VisualStudioMag "},
{"href":"http://www.infoworld.com/","title":"InfoWorld"},
{"href":"http://www.webtechniques.com/","title":"NewArchitect"},
{"href":"https://ravendb.net/learn","title":"RavenDb"},
{"href":"http://www.sqlmag.com/","title":"ITPro Magazine"}
]