[
{"href":"https://www.livenewsworld.com/fox-news-live-stream/","title":"FoxNews TV"},
{"href":"http://tunein.com/","title":"Radio TuneIn"},
{"href":"http://tunein.com/radio/Conservative-c57917/","title":"Conservative Talk"},
{"href":"https://americasvoice.news/","title":"War Room America's Voice"},
{"href":"http://www.talkstreamlive.com","title":"TalkStream live"},

{"href":"http://utakmice.net/tenis/","title":"TENNIS UTAKMICE"},


{"href":"https://podcasts.google.com/search/no%20agenda","title":"No Agenda"},
{"href":"https://podcasts.google.com/search/mark%20simone","title":"Mark Simone"},
{"href":"https://podcasts.google.com/search/ask%20a%20spaceman","title":"Ask A Spaceman"},
{"href":"https://podcasts.google.com/search/dot%20net%20rocks","title":"DotNet Rocks!"},
{"href":"https://podcasts.google.com/search/security%20now","title":"Security Now"},



{"href":"http://streamuruguay5.blogspot.com/","title":"StreamUruguay5"},

{"href":"http://www.rojadirecta.me/","title":"RojaDirecta ME"},
{"href":"http://rojadirecta.su/","title":"RojaDirecta SU"},
{"href":"http://www.tarjetaroja.eu/","title":"TarjetaRoja"},

{"href":"http://www.freeintertv.com/view/id-2023","title":"CSPAN"},
{"href":"http://www.freeintertv.com/view/id-2814","title":"CSPAN2"},
{"href":"http://www.freeintertv.com/view/id-2815","title":"CSPAN3"},

{"href":"http://www.rtve.es/noticias/directo-la-1/","title":"RTVE.ES San Fermin"},
{"href":"http://www.radios.co.ve/rcr-caracas/#","title":"RCR Vz"},
{"href":"http://www.radios.co.ve/actualidad-caracas/#","title":"Union Radio Caracas Vz"},
{"href":"http://streema.com/radios/play/93215","title":"Union Radio Barqui Vz"},
{"href":"http://streema.com/radios/play/38123","title":"Union Radio P.Ordaz Vz"},


{"href":"https://www.hispantv.com/directo","title":"Hispantv"},
{"href":"https://www.cronoco.com/2014/03/vtv-en-vivo-vea-venezolana-de.html","title":"VTV Vz"},
{"href":"https://www.youtube.com/watch?v=TQrzPbL9Dh4&feature=youtu.be","title":"Telesur"},
{"href":"https://www.raiplay.it/dirette/rainews24","title":"RAI"},

{"href":"http://cricfree.ws/update/bt1","title":"BT 1"},
{"href":"http://yoursports.stream/live.php?v=fs1","title":"Fox Sports 1"},
{"href":"https://www.rt.com/on-air/","title":"Russia Today"},
{"href":"https://www.dw.com/en/media-center/live-tv/s-100825?channel=1","title":"DWTV (Deutsche Welle)"},

{"href":"https://www.bfmtv.com/mediaplayer/live-video/","title":"BFMtv France"},

{"href":"https://www.youtube.com/watch?v=XOacA3RYrXk","title":"SkyTV"},
{"href":"http://www.freeintertv.com/view/id-1695","title":"Fox Sports"},
{"href":"http://totalsport.me/schedule.txt","title":"TotalSport"},
{"href":"http://www.livenewsmag.com/bbc-news-uk-live-stream/","title":"BBC News"},
{"href":"http://tv-online.us/infowars-live-stream/","title":"InfoWars"},
{"href":"https://www.nasa.gov/nasalive","title":"NASA Live"},
{"href":"https://eol.jsc.nasa.gov/ESRS/HDEV/","title":"NASA Remote Sensing Unit"},
{"href":"https://www.aljazeera.com/live/","title":"AlJazeera"},
{"href":"http://www.mrsoccers.com/","title":"MrSoccers"},
{"href":"https://www.totalsportek.com/","title":"totalSporTek"},

{"href":"http://live2all.com/","title":"Live2All"},
{"href":"http://www.epctv.com/","title":"Epctv"},

{"href":"http://www.desifree.tv/sky-news/","title":"DesiFree"},
{"href":"https://video.sky.it/news/diretta","title":"SkyNews (all in italian)"},
{"href":"http://123tv.live/category/united-states-usa/","title":"123tv"},
{"href":"https://livestream.com/watch/browse/sports","title":"LiveStream"},
{"href":"https://www.olweb.tv/sitemap.xml","title":"Olweb"},
{"href":"http://www.exstreams.net","title":"Exstreams"},
{"href":"https://ssl.ustreamix.com/","title":"UstreamMix"},
{"href":"https://tvplayer.com/watch","title":"TV Player (uk ip hotmail PE#5)"},
{"href":"http://sako-tv.blogspot.com/2017/03/polska-telewizja-online.html","title":"SakoTv btsport"}, 
{"href":"http://www.sdw-net.me/","title":"SDW"},
{"href":"https://veohtube.com/genre/LIVE%20TV","title":"Veohtube"},
{"href":"http://tv4embed.com/uk/","title":"Tv4embed (UK)"},
{"href":"http://tv4embed.com/usa/","title":"Tv4embed (USA)"},
{"href":"http://tv4embed.net/","title":"Tv4embed Net"},

{"href":"https://www.reddit.com/r/LiveTvLinks/comments/asojj8/sports_channels/","title":"Reddit tv list"},
{"href":"http://unblocked.is/tv","title":"Unblocked.is"},
{"href":"http://nowwatchtvlive.ws/","title":"NowWatchLive"},
{"href":"http://www.tvball7.com/bt-sport-2","title":"TVball5 btsport"},
{"href":"http://www.hadetv.com/","title":"HadeTv Indonesia"},
{"href":"http://www.utfifa17.com/2018/03/bein-sports.html","title":"Utffa BEin 123456 "},
{"href":"http://www.tvanda.com/2017/11/bein-sport.html","title":"TVanda BEin Chad "},
{"href":"http://www.skytivi.com/bein-sports","title":"SkyTiVi BEin Chad "},
{"href":"http://shangaza.net/forums","title":"Shangaza BEin BT"},
{"href":"http://www.time4tv.net/schedule.php","title":"Time4Tv"},
{"href":"https://www.strikeout.nu/lookup/espn","title":"StrikeOut"},
{"href":"http://www1.cricbox.net/","title":"CricBox"},
{"href":"http://www3.crichd.in/bein-sports-2-france-live-stream-2/","title":"Crichj"},
{"href":"https://www.streamlive.to/","title":"Streamlive"},
{"href":"http://www.streamendous.com/sportsch.php?bt1","title":"Streamendous"},
{"href":"http://www.fromhot.com/","title":"Fromhot.com"},
{"href":"http://superhd.me/","title":"SuperHd"},
{"href":"http://music-tv.in/?tab=usa%20tv&live=espn%202%20usa%20live","title":"Music Tv USA Ch"},
{"href":"http://atdhes.eu/","title":"Atdhes"},
{"href":"https://watchsportonline.cc/category/tennis/","title":"Watchsportonline"},
{"href":"https://motorsports-stream.com/next-live-races/","title":"Motorspots and other"},
{"href":"https://tennis-stream.net/watch-live-stream-6/","title":"Tennis stream and other"},
{"href":"https://sportlemon24.com/","title":"Sportlemmon Tennis stream and other"},
{"href":"http://livetv.sx/enx/","title":"LiveTv (all live sports)"},
{"href":"https://m.liveonlinetv247.info/","title":"Live Mobile 247 (BEin BT Sport)"},
{"href":"http://mygoodstream.pw/","title":"MyGoodStream (sports)"},
{"href":"https://www.vipleague.lc/","title":"VIP League (sports)"},
{"href":"https://www.vipbox.fi/","title":"VIP Box (sports)"},
{"href":"https://www.viprow.net/","title":"VIP Row"},
{"href":"https://firstsrowsports.tv/","title":"FirstRow"},
{"href":"http://streamshunters.com/","title":"StreamHunters (sports)"},
{"href":"http://www.streamgaroo.com/television/united-states/","title":"Streamgaroo"},


{"href":"http://yoursports.stream/","title":"Yoursports(sports/everything)"},
{"href":"https://daddylive.live/index.php","title":"DaddyLive"},
{"href":"http://www.istreamsport.com/","title":"iStreamSport"},
{"href":"http://nflstream.io/espn-live-stream-online-live/stream-1","title":"NflStream"},
{"href":"http://nflstreams.link/","title":"NFLStreams.link>"},
{"href":"http://chanfeed.com/","title":"Chanfeed.com"},
{"href":"http://nowagoal.com","title":"Nowagoal"},
{"href":"http://www.720pstream.me/","title":"720pstream (all live sports)"},
{"href":"https://www.stream2watch.org/","title":"Stream2watch (sports)"},
{"href":"https://www.mamahd.org/","title":"MamaHd"},
{"href":"http://buffstream.net/","title":"Buffstream.net NFL"},
{"href":"http://buffstream.live/","title":"Buffstream.live"},
{"href":"http://buffstreamz.com/nfl-streams/","title":"NFL-Streams"},
{"href":"https://buffstream.com/watch/nfl-live.php","title":"Buffstream.com (chrome wide)"},
{"href":"http://sportstreamshd.com/","title":"Sportstreamshd"},


{"href":"http://www.livehere.one/canale-5-italia-1-rete-4-rai-1-dmax-realtime-diretta-streaming-estero/","title":"LiveHere ita"},
{"href":"http://okteve.com/categories/","title":"OkTeve"},
{"href":"https://wwitv.com/portal.htm","title":"WWitv"},
{"href":"http://oklivetv.com/","title":"OkLiveTv"},
{"href":"http://freetvall.live/","title":"FreeTvAll"},
{"href":"http://livetvcafe.me/","title":"LiveTvCafe"},
{"href":"http://www.freeintertv.com/view/id-2566","title":"Free internet TV"},
{"href":"http://ufreetv.com/","title":"UFreeTV"},
{"href":"http://ustv247.com/","title":"UStv 247"},
{"href":"http://ustvgo.com/","title":"UStv Go"},
{"href":"http://watchnewslive.tv/","title":"WatchNewsLive"},
{"href":"https://wwitv.com/portal.htm","title":"WWItv"},
{"href":"https://tklist.us/channels/","title":"Tklist"},
{"href":"http://sports24.club/tv/","title":"Sports24"},


{"href":"http://livetvmania.net/","title":"Live TV Mania"},
{"href":"http://www.livenewsmag.com/","title":"Livenews Channel(s)"},
{"href":"https://www.livenewson.com/united-kingdom/sky-news-hd.html","title":"LivenewsOn"},
{"href":"http://www.zahistationtv.com/","title":"Zahistation tv"},

 
{"href":"http://www.mclaughlin.com/","title":"McLaughlinGr"}, 
{"href":"http://freshair.npr.org/","title":"FreshAir"},
{"href":"http://www.thislife.org/","title":"ThisAmerLife"},
{"href":"http://www.theconnection.org/shows/","title":"TheConnection"}, 
{"href":"http://fora.tv/","title":"Fora.Tv"}
]
