[

{"href":"https://twitter.com/JackPosobiec","title":"Jack Posobiec"},
{"href":"https://twitter.com/TuckerCarlson","title":"Tucker Carlson"},
{"href":"https://twitter.com/RobertKennedyJr","title":"RFK Jr"},
{"href":"https://twitter.com/TheBabylonBee","title":"The BabylonBee"},
{"href":"https://twitter.com/MattWalshBlog","title":"Matt Walsh"},
{"href":"https://twitter.com/elonmusk","title":"Elon Musk"},
{"href":"https://twitter.com/SpaceX","title":"SpaceX"},
{"href":"https://twitter.com/jsolomonReports","title":"John Solomon"},
{"href":"https://twitter.com/marklevinshow","title":"Mark Levin"},
{"href":"https://twitter.com/ChanelRion","title":"Chanel Rion"},
{"href":"https://twitter.com/MarcoPolo501c3","title":"Marco Polo"},
{"href":"https://twitter.com/mirandadevine","title":"Miranda Devine"},
{"href":"https://twitter.com/JonathanTurley","title":"Jonathan Turley"},
{"href":"https://twitter.com/SchmittNYC","title":"Rob Schmitt Newsmax"},
{"href":"https://twitter.com/wajacobson","title":"Wm Jacobson (LI)"},
{"href":"https://twitter.com/DouglasKMurray","title":"Douglas Murray"},
{"href":"https://twitter.com/VDHanson","title":"VD Hanson"},
{"href":"https://twitter.com/realannapaulina","title":"Anna Paulina"},
{"href":"https://twitter.com/RepMTG","title":"RepMTG"},
{"href":"https://twitter.com/Techno_Fog","title":"TechnoFog"},
{"href":"https://twitter.com/HansMahncke","title":"Hans Mahncke"},
{"href":"https://twitter.com/paulsperry_","title":"Paul Sperry (Real Clear)"},
{"href":"https://twitter.com/NateSilver538","title":"Nate Silver (538)"},
{"href":"https://twitter.com/FiveThirtyEight","title":"538"},
{"href":"https://twitter.com/TheAtlantic","title":"The Atlantic"},
{"href":"https://twitter.com/NewYorker","title":"The New Yorker"},
{"href":"https://twitter.com/RebelNewsOnline","title":"Rebel News"},
{"href":"https://twitter.com/RevolverNewsUSA","title":"Revolver News"},
{"href":"https://twitter.com/KashsCorner","title":"Kash Patel"},
{"href":"https://twitter.com/RepBoebert","title":"Lauren Boebert"},
{"href":"https://twitter.com/naomirwolf","title":"Neomi Wolf"},
{"href":"https://twitter.com/mtaibbi","title":"Matt Taibbi"},
{"href":"https://twitter.com/shellenberger","title":"Michael Shellenberger"},
{"href":"https://twitter.com/MZHemingway","title":"Mollie Hemingway"},
{"href":"https://twitter.com/RepMattGaetz","title":"Matt Gaetz"},
{"href":"https://twitter.com/TomFitton","title":"Tom Fitton"},
{"href":"https://twitter.com/Barnes_Law","title":"Robert Barnes"},
{"href":"https://twitter.com/julie_kelly2","title":"Julie Kelly"},
{"href":"https://twitter.com/RepAndyBiggsAZ","title":"Rep Andy Biggs AZ"},
{"href":"https://twitter.com/chiproytx","title":"Rep Chip Roy TX"},
{"href":"https://twitter.com/EvaVlaar","title":"Eva Vlaardingerbroek"},
{"href":"https://twitter.com/TuckerCarlson","title":"Tucker Carlson"},
{"href":"","title":""},
{"href":"","title":""},
{"href":"","title":""},
{"href":"","title":""},
{"href":"","title":""},
{"href":"","title":""},
{"href":"","title":""},
{"href":"","title":""},
{"href":"","title":""},
{"href":"","title":""},
{"href":"","title":""},
{"href":"","title":""}


]