[

{"href":"https://twitter.com/michaelpleahy","title":"Michael Patrick Leahy"},
{"href":"https://twitter.com/RobertKennedyJr","title":"RFK Jr"},


{"href":"https://twitter.com/TheBabylonBee","title":"The BabylonBee"},
{"href":"https://twitter.com/jsolomonReports","title":"John Solomon"},
{"href":"https://twitter.com/elonmusk","title":"Elon Musk"},
{"href":"https://twitter.com/SpaceX","title":"SpaceX"},

{"href":"#","title":"---------CONSERVATIVE WOMEN------------"},
{"href":"https://twitter.com/chanelrion/","title":"Chanel Rion"},
{"href":"https://twitter.com/julie_kelly2","title":"Julie Kelly"},
{"href":"https://twitter.com/LauraLoomer","title":"Laura Loomer"},
{"href":"https://twitter.com/laralogan","title":"Lara Logan"},
{"href":"https://twitter.com/TalkMullins","title":"Heather Mullins"},
{"href":"https://twitter.com/annvandersteel","title":"Ann Vandersteel"},
{"href":"https://twitter.com/LoomerReport","title":"Loomer Report"},
{"href":"https://twitter.com/mirandadevine","title":"Miranda Devine"},
{"href":"https://twitter.com/MZHemingway","title":"Mollie Hemingway"},
{"href":"https://twitter.com/EmeraldRobinson","title":"Emerald Robinson"},
{"href":"https://twitter.com/EvaVlaar","title":"Eva Vlaardingerbroek"},
{"href":"https://twitter.com/CarolineWren","title":"Caroline Wren"},
{"href":"https://twitter.com/pnjaban","title":"Harmeet Dhillon"},
{"href":"https://twitter.com/bungarsargon/","title":"Batya Ungar-Sargon (Newsweek)"},

{"href":"","title":""},
{"href":"https://twitter.com/HansMahncke","title":"Hans Mahncke"},
{"href":"https://twitter.com/paulsperry_","title":"Paul Sperry (Real Clear)"},
{"href":"https://twitter.com/ScottPresler","title":"Scott Pressler (The Persistance)"},
{"href":"https://twitter.com/Rach_IC","title":"Rachel Alexander"},
{"href":"https://twitter.com/Cernovich?ref_url=/","title":"Mike Cernovich"},
{"href":"https://twitter.com/MattWalshBlog","title":"Matt Walsh"},

{"href":"","title":""},
{"href":"https://twitter.com/Peoples_Pundit","title":"Richard Baris (People's Pundit)"},
{"href":"https://twitter.com/NateSilver538","title":"Nate Silver (538)"},
{"href":"https://twitter.com/FiveThirtyEight","title":"538"},
{"href":"https://twitter.com/TheAtlantic","title":"The Atlantic"},
{"href":"https://twitter.com/NewYorker","title":"The New Yorker"},
{"href":"https://twitter.com/RebelNewsOnline","title":"Rebel News"},
{"href":"https://twitter.com/RevolverNewsUSA","title":"Revolver News"},

{"href":"","title":""},
{"href":"#","title":"---------VACCINE------------"},
{"href":"https://twitter.com/naomirwolf","title":"Neomi Wolf"},
{"href":"https://twitter.com/RWMaloneMD","title":"Robert Malone MD"},
{"href":"https://twitter.com/DowdEdward","title":"Ed Dowd"},
{"href":"https://twitter.com/stkirsch","title":"Steve Kirsch"},
{"href":"https://twitter.com/MdBreathe","title":"Mary Taley Bowden MD"},
{"href":"https://twitter.com/P_McCulloughMD","title":"Peter McCullough MD"},
{"href":"https://twitter.com/brownstoneinst/","title":"Brownstone Institute"},
{"href":"https://twitter.com/jeffreyatucker","title":"Jeffrey Tucker"},
{"href":"https://twitter.com/unhealthytruth","title":"Erin Elizabeth Health Nut News"},

{"href":"","title":""},
{"href":"#","title":"---------CONSERVATIVE MEN------------"},
{"href":"https://twitter.com/RealEJAntoni","title":"AJ Antoni"},
{"href":"https://twitter.com/michaelpleahy","title":"Michael Patrick Leahy"},
{"href":"https://twitter.com/ChuckCallesto","title":"Chuck Callesto"},
{"href":"https://twitter.com/TomFitton","title":"Tom Fitton"},
{"href":"https://twitter.com/Barnes_Law","title":"Robert Barnes"},
{"href":"https://twitter.com/JonathanTurley","title":"Jonathan Turley"},
{"href":"https://twitter.com/shipwreckedcrew","title":"Shipwreckedcrew"},
{"href":"https://twitter.com/Techno_Fog","title":"TechnoFog"},
{"href":"https://twitter.com/mrddmia","title":"Mike Davis"},
{"href":"https://twitter.com/KashsCorner","title":"Kash Patel"},
{"href":"https://twitter.com/AndrewCMcCarthy","title":"Andy McCrthy"},
{"href":"https://twitter.com/MarcoPolo501c3","title":"Marco Polo"},
{"href":"https://twitter.com/SchmittNYC","title":"Rob Schmitt Newsmax"},
{"href":"https://twitter.com/wajacobson","title":"Wm Jacobson (LI)"},
{"href":"https://twitter.com/DouglasKMurray","title":"Douglas Murray"},
{"href":"https://twitter.com/VDHanson","title":"Victor D Hanson"},

{"href":"","title":""},
{"href":"#","title":"---------FREEDOM CAUCUS------------"},
{"href":"https://twitter.com/JDVance1","title":"SEN J.D. Vance OH"},
{"href":"https://twitter.com/RepHageman","title":"Rep Harriet Hageman WY"},
{"href":"https://twitter.com/RepNancyMace","title":"Rep Nancy Mace SC"},
{"href":"https://twitter.com/RepAndyBiggsAZ","title":"Rep Andy Biggs AZ"},
{"href":"https://twitter.com/chiproytx","title":"Rep Chip Roy TX"},
{"href":"https://twitter.com/RepThomasMassie","title":"Rep Thomas Massie KY"},
{"href":"https://twitter.com/ByronDonalds","title":"Rep Byron Donalds SWFL"},
{"href":"https://twitter.com/WesleyHuntTX","title":"Rep Wesley Hunt TX"},
{"href":"https://twitter.com/RepBoebert","title":"Rep Lauren Boebert CO"},
{"href":"https://twitter.com/realannapaulina","title":"Rep Anna Paulina FL"},
{"href":"https://twitter.com/RepMTG","title":"Rep MTG GA"},
{"href":"https://twitter.com/RepMattGaetz","title":"Rep Matt Gaetz FL"},
{"href":"https://twitter.com/RepRosendale","title":"Rep Matt Rosendale MT"},

{"href":"","title":""},
{"href":"https://twitter.com/bariweiss","title":"Bari Weiss"},
{"href":"https://twitter.com/mtaibbi","title":"Matt Taibbi"},
{"href":"https://twitter.com/shellenberger","title":"Michael Shellenberger"},
{"href":"https://twitter.com/EricRWeinstein","title":"Eric Weinstein"},
{"href":"https://twitter.com/RealJamesWoods","title":"James Woods"},

{"href":"","title":""},
{"href":"","title":""}


]